"""Init

Revision ID: 01b0166cba7f
Revises: 59f2a05ac3e6
Create Date: 2023-02-19 22:46:49.246517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b0166cba7f'
down_revision = '59f2a05ac3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
