"""Init

Revision ID: 103788abaf08
Revises: 3647bdf1f909
Create Date: 2023-02-19 17:18:53.118774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103788abaf08'
down_revision = '3647bdf1f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
