"""Init

Revision ID: 3647bdf1f909
Revises: 8b65148e462d
Create Date: 2023-02-19 16:18:40.631527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3647bdf1f909'
down_revision = '8b65148e462d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
