"""Init

Revision ID: 3712f94dcbc9
Revises: a1da39857d67
Create Date: 2023-02-19 17:25:51.057165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3712f94dcbc9'
down_revision = 'a1da39857d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
