"""Init

Revision ID: 3bbdb36c0b30
Revises: 97d31f91f014
Create Date: 2023-03-06 22:41:15.565209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbdb36c0b30'
down_revision = '97d31f91f014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authusers', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authusers', 'confirmed')
    # ### end Alembic commands ###
