"""Init

Revision ID: 3f7fc1859f5d
Revises: 01b0166cba7f
Create Date: 2023-02-19 23:52:39.073873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7fc1859f5d'
down_revision = '01b0166cba7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
