"""Init

Revision ID: 5770fefc6466
Revises: 103788abaf08
Create Date: 2023-02-19 17:21:13.808748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5770fefc6466'
down_revision = '103788abaf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=False))
    op.drop_column('users', 'birthaday')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('birthaday', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
