"""Init

Revision ID: 59f2a05ac3e6
Revises: 3712f94dcbc9
Create Date: 2023-02-19 22:28:03.837731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f2a05ac3e6'
down_revision = '3712f94dcbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
