"""Init

Revision ID: 74c5c6d1d0f0
Revises: 92a17efc06f4
Create Date: 2023-02-20 02:40:25.440153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c5c6d1d0f0'
down_revision = '92a17efc06f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
