"""Init

Revision ID: 8b65148e462d
Revises: 0113f7a3fe4f
Create Date: 2023-02-19 14:52:39.995436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b65148e462d'
down_revision = '0113f7a3fe4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
