"""Init

Revision ID: 92a17efc06f4
Revises: 3f7fc1859f5d
Create Date: 2023-02-20 02:24:58.511310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92a17efc06f4'
down_revision = '3f7fc1859f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
